### ISSUE TITLE
using rest framework's IsAuthenticated break the condition evaluation in django 1.10

### ISSUE THREAD

**Issue by rouk1** [caxap/rest_condition#9]
If you use `rest_framework.permissions.IsAuthenticated` the reduce operator will crash [here](https://github.com/caxap/rest_condition/blob/master/rest_condition/permissions.py#L97) because Django now returns a `CallableBool`.

This could be fixed by adding a callable test just after getting the result.

```
        if hasattr(result, '__call__'):
            result = result()
```

**Comment by caxap** [comment]
Fixed in v1.0.3 https://github.com/caxap/rest_condition/commit/ce2ced84f67dbb9b371a36311006723a749e1e8f
